In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [9]:
# Load your CSV
df = pd.read_csv('./data/up_sample.csv')
df.head()

,SOLD_TO_CUSTOMER_ID,ACCOUNTID,FIRST_NAME,LAST_NAME,EMAIL,CONTACT_TITLE,INDUSTRY,CHANNEL,MATERIAL_PCAT_DESC,PCAT_BILL_QTY,PCAT_GSAR,PCAT_PM,PCAT_COST,TARGET_1
0,5973628,0017000000QueHvAAJ,Dariusz,Czyszczon,dc.invest@yahoo.com,General Manager,HS - HOSPITALITY,Inside Sales,Personal Care Amenities,18,1232.22,501.97,730.25,GENERAL_MANAGER
1,6034706,0017000000RcOMTAA3,Luis,Figueroa,huntingtonreserve@gotpi.org,Maintenance Supervisor,MH - MULTIFAMILY,Field Sales,Lubricants,11,113.18,47.78,65.40,ENGINEERING
2,846300,0017000000RoHzgAAF,Tom,Bay,thomas.bay@humangood.org,Maintenance Dept.,HL - HEALTHCARE,Field Sales,Range Hood Filters,10,147.86,127.07,20.79,ENGINEERING
3,14769107,0013900001VWnLKAA1,Daniel,Montesino,dmontesino@redpeak.com,Maintenance Technician,MH - MULTIFAMILY,Field Sales,Thermostats & Temperature Ctrl,11,511.24,248.92,262.32,ENGINEERING
4,13647483,00170000018zBQUAA2,Jason,Reich,pxfm@gulfcorpservices.com,Maintenance Manager,MH - MULTIFAMILY,Marketing,Drain Cleaning Equipment,1,117.29,50.80,66.49,ENGINEERING

In [10]:
# Aggregate by customer and category
pivot = df.pivot_table(
    index='ACCOUNTID', 
    columns='MATERIAL_PCAT_DESC', 
    values='PCAT_BILL_QTY',
    aggfunc='sum', 
    fill_value=0
).reset_index()

In [11]:
# Merge back the target
targets = df[['ACCOUNTID', 'TARGET_1']].drop_duplicates()
dataset = pivot.merge(targets, on='ACCOUNTID', how='left')

In [12]:
# Encode the TARGET_1 if needed
dataset['TARGET_1_CODED'] = LabelEncoder().fit_transform(dataset['TARGET_1'])

In [15]:
dataset.head()

,ACCOUNTID,"1"" Aluminum Cordless","1"" LF Vinyl Cordless",1‚Äù Deluxe Cordless,"2"" Deluxe Cordless",ADA Communications,Aerators,Air Filtration,"Air Handlers, Furnaces & Coils","Artwork, Clocks & Mirrors",...,Window Covering Accessories,Window Hardware,Window Shades & Rods,Wiring Devices,Wiring Devices - GFCIs,Wiring Devices - Receptacles,Wiring Supplies,Yard Signs,TARGET_1,TARGET_1_CODED
0,0011O00002BEf2jQAD,0,0,0,0,0,2,36,6,0,...,0,2,0,0,8,0,0,0,ENGINEERING,0
1,0011O00002DFoYIQA1,0,0,0,2,0,0,49,0,0,...,0,0,0,1,0,1,0,0,ENGINEERING,0
2,0011O00002KauhmQAB,0,0,0,0,0,0,0,0,0,...,0,12,0,0,0,0,0,0,ENGINEERING,0
3,0011O00002MstoVQAR,0,0,0,0,0,10,22,0,0,...,18,0,0,16,0,12,4,0,ENGINEERING,0
4,0011O00002SvZd6QAF,0,0,0,0,0,0,14,0,0,...,0,0,0,0,0,1,0,0,ENGINEERING,0